// <auto-generated />
namespace DevCamps.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCampTypeTitleSlug : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCampTypeTitleSlug));
        
        string IMigrationMetadata.Id
        {
            get { return "201302072016180_AddCampTypeTitleSlug"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
